import Head from "next/head";
import Link from "next/link";
import { api } from " y/utils/api";
import { Container } from "postcss";
import { useRouter } from "next/router";
import { useUser } from "@clerk/nextjs";

export default function Home() {
  const user = useUser();
  console.log(user);
  
  //const { data,isLoading } = api.posts.getAll.useQuery();
  return (
    <>
      <Head>
        <title>FML Hackathon</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text text-center text-slate-100">
        <div className="flex justify-center flex-row space-x-8 my-6 mx-40">
        <div className="container-sm bg-white border-white border-2 rounded-md h-60 w-80">
          <div className="text-black text-left font-light text-lg">
            <label className="text-black text-center font-light font-serif">from</label>
            <div className="relative flex flex-col">
              <button>Dropdown</button>
            </div>
          </div>
        </div>
        <div className ="my-28">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
        <path strokeLinecap="round" strokeLinejoin="round" d="M7.5 21L3 16.5m0 0L7.5 12M3 16.5h13.5m0-13.5L21 7.5m0 0L16.5 12M21 7.5H7.5" />
        `</svg>

        </div>
        
        <div className="container-sm bg-white border-white border-2 rounded-md h-60 w-80 ">
          <div className="text-black text-left font-light text-lg">
            <label className=" font-serif">Destination</label>
           
          </div>
        </div>
        <div className="container-sm bg-white border-white border-2 rounded-md h-60 w-80 ">
          <div className="text-black text-left font-light text-lg">
            <label className="text-black font-light font-serif ">Travellers</label>
          </div>
        </div>
        </div>
      </main>
    </>
  );
}