import Head from "next/head";
import Link from "next/link";
import { api } from " y/utils/api";
import Image from 'next/image'
import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { useRouter } from "next/router";
export default function Home() {
const router = useRouter()
const user = useUser();

//const { data } = api.posts.getAll.useQuery()
  
  return (
    <>
      <Head>
        <title>FML Hackathon</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen gap-0">
        
      </main>
    </>
  );
}