import Head from "next/head";
import Link from "next/link";
import { api } from " y/utils/api";
import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import React, { useState } from 'react';
import DatePicker from 'react-datepicker';
import 'react-datepicker/dist/react-datepicker.css';
import { Calendar } from "react-calendar"; 

export default function Home() {
return (
    <>
      <Head>
        <title>FML Hackathon</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text text-left">
      <div className="flex flex-row space-x-8 my-6 mx-40">
        <div className="container-sm bg-white border-white border-2 rounded-md h-60 w-80 text-black ">
          Departure
        </div>

        <div className ="my-28">
        </div>
        <div className="container-sm bg-white border-white border-2 rounded-md h-60 w-80 text-black ">
          Return
        </div>


        <div className="container-sm bg-white border-white border-2 rounded-md h-60 w-80 text-black ">
          Travellers&Class
        </div>

    </div>
    </main>
    </>
)
}