import Head from "next/head";
import Link from "next/link";
import { api } from " y/utils/api";
import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

export default function Home() {
  
  const user = useUser();

  const { data } = api.posts.getAll.useQuery()
  return (
    <>
      <Head>
        <title>FML Hackathon</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text text-center text-slate-100">
      <div>
        {!user.isSignedIn && <SignInButton />}
        {!!user.isSignedIn && <SignOutButton />}
      </div>
      <div>
        { data?.map((post) => (
          <div key={post.id}>{post.content}</div>
        ))}
      </div>
      </main>
    </>
  );
}
