import React from 'react';
import Head from 'next/head';

export default function Reward() {
  return (
    <>
      <Head>
        <title>FML Hackathon</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text text-center text-slate-100 ">
        <div className="w-full h-screen flex flex-col items-center justify-center">
          <h1 className="text-4xl font-bold mb-8">REWARDS</h1>
          <table className="w-full border-collapse">
            <tbody>
              {Array.from({ length: 5 }).map((_, rowIndex) => (
                <tr key={rowIndex}>
                  {Array.from({ length: 6 }).map((_, colIndex) => (
                    <td key={colIndex} className="border p-2">
                      {(rowIndex * 6) + colIndex + 1}
                      <br />
                      <span role="img" aria-label="checkmark">
                        &#x2714;
                      </span>
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
}
